//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaTienda2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaDeVenta
    {
        public int Id { get; set; }
        public long Cantidad { get; set; }
        public double PrecioDeVenta { get; set; }
    
        public virtual StockSet StockSet { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
