//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaTienda2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockSet()
        {
            this.LineaDeVenta = new HashSet<LineaDeVenta>();
        }
    
        public int Id { get; set; }
        public string Cantidad { get; set; }
        public int Color_Id { get; set; }
        public int Talle_Id { get; set; }
        public int Producto_Id { get; set; }
    
        public virtual ColorSet ColorSet { get; set; }
        public virtual ProductoSet ProductoSet { get; set; }
        public virtual TalleSet TalleSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaDeVenta> LineaDeVenta { get; set; }
    }
}
